apiVersion: apps/v1
kind: Deployment
metadata:
  name: htv-api
  namespace: htv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htv-api
  template:
    metadata:
      labels:
        app: htv-api
    spec:
      volumes:
        - name: htv-api-jwt-secret
          secret:
            secretName: htv-api-jwt-secret
      containers:
        - name: htv-api
          image: registry.digitalocean.com/mycc/ab-test:latest
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sequelize db:migrate"]
          ports:
          - containerPort: 80
          volumeMounts:
          - name: htv-api-jwt-secret
            mountPath: "/app/private.pem"
            subPath: private.pem
          - name: htv-api-jwt-secret
            mountPath: "/app/public.pem"
            subPath: public.pem
          env:
          - name: NODE_ENV
            value: "production"
          - name: FRONTEND_URL
            value: "https://htv.anthonybudd.io"
          - name: BACKEND_URL
            value: "https://htv-api.anthonybudd.io/api/v1"
          - name: PORT
            value: "80"
          - name: PRIVATE_KEY_PATH
            value: "/app/private.pem"
          - name: PUBLIC_KEY_PATH
            value: "/app/public.pem"
          - name: DB_HOST
            value: "ab-api-db-postgresql-nyc3-50393-do-user-23204408-0.f.db.ondigitalocean.com"
          - name: DB_PORT
            value: "25060"
          - name: DB_USERNAME
            value: "doadmin"
          - name: DB_DATABASE
            value: "defaultdb"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: htv-api-secrets
                key: DB_PASSWORD
