apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: htv-api-ingress
  namespace: htv-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-ingress-class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/client-max-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - htv-api.anthonybudd.io
    secretName: htv-api-tls
  rules:
    - host: htv-api.anthonybudd.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: htv-api
                port:
                  number: 80
