apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: htv-api
spec:
  dnsNames:
  - 'htv-api.anthonybudd.io'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: htv-api-tls