// Database types (generated by Prisma)
export type { 
  Company, 
  User, 
  Request, 
  Comment,
  UserRole,
  Priority,
  Status 
} from '@prisma/client'

// API Response types
export interface ApiResponse<T = any> {
  data?: T
  error?: string
  message?: string
}

// Request form types
export interface CreateRequestData {
  title: string
  description: string
  category: string
  priority?: Priority
}

// Linear webhook types
export interface LinearWebhookPayload {
  action: string
  data: {
    id: string
    identifier: string
    title: string
    state: {
      name: string
      type: string
    }
  }
  organizationId: string
  webhookTimestamp: number
}

// Real-time event types
export interface RequestUpdateEvent {
  requestId: string
  status: Status
  updatedAt: string
  companyId: string
}

// UI Component types
export interface SelectOption {
  label: string
  value: string
}

// Auth types
export interface CompanyContext {
  companyId: string
  companyName: string
  role: UserRole
}